### ISSUE TITLE
Grid/Collection: *absolute displacement threshold* is not adhered to

### ISSUE THREAD

**Issue by arve0** [fiji/Stitching#32]
When stitching I often get weird results due to missing signal in overlap between images:

![stitched--u00--v00--c00--z00-kopi](https://cloud.githubusercontent.com/assets/4810521/7592804/e3d0916e-f8d5-11e4-9616-110417d76b25.png)

Seems like the setting _absolute displacement threshold_ is not adhered.

What I expect: Should remove links between images if the absolute displacement is higher than this value, ref http://fiji.sc/Image_Stitching

**Comment by arve0** [comment]
Also, a possible improvement would be to chose the median displacement for those images which are unable to fall below the given *absolute displacement threshold*. In this way one fails gracefully, and has often (at least for microscope images) chose the right displacement.

**Comment by imagejan** [comment]
IIUC, the *absolute displacement threshold* is calculated for the whole set of tiles to reflect the displacement between each optimal overlap of pairs and the resulting overlap after global optimization. There seems to be no option to limit the displacement from the original grid position or position defined by metadata.
See also this [discussion on the forum](http://forum.imagej.net/t/limit-the-tile-displacement-in-stitching/424).
