### ISSUE TITLE
Batch runs?

### ISSUE THREAD

**Issue by SirSteel** [fiji/Stitching#36]
I am a python native programmer and don't know much java. But as far as I can read from the code, the GUI is embedded in the main code. Is there something I missed? Is there a way to run this as a batch on a series of folders? I would want the same settings for all folders, so basically the only thing that would change would be the directory setting.
I am not that familiar with macros, could it be done that way?

**Comment by StephanPreibisch** [comment]
Hi, it can be done using the ImageJ Macro Recorder and modifying the recorded command. To do that use Plugins > Macro > Record and choose the language accordingly.

Hope this helps,
Stephan

**Comment by SirSteel** [comment]
Thank you, it does!
