### ISSUE TITLE
Grid stitching column grid

### ISSUE THREAD

**Issue by schroef** [fiji/Stitching#45]
Just tried grid stitch using column by column > down & right using these settings;

![screen shot 2017-08-02 at 2 11 40 pm](https://user-images.githubusercontent.com/6923008/28887867-af2547f6-778c-11e7-939f-bb087e0b3b40.png)

My images are name according to this grid so 1-1, 1-2, 1-2, 1-4 etc etc. When i use this for filename, Thea_1355File name..._{x}-{y}_8-8.png

I receive this error;
ERROR: Cannot find file: '/Users/romboutversluijs/Desktop/region/Thea_1355File name..._{x}-{y}_8-8.png' - abort stitching.
ERROR: Error during tile discovery, or invalid grid type. Aborting.

Hiow can we use custom named files correctly?

**Comment by StephanPreibisch** [comment]
Hi, it is explained in the documentation: http://imagej.net/Image_Stitching#Grid.2FCollection_Stitching

"The grid stitching assumes that the tiles which are arranged in any kind of grid are incrementally numbered. The First tile index i defines the number of the first tile in your approximate tile configuration (see figure above)."

"The next entry File name for tiles in the dialog is used to tell the plugin how to find the images which are in the grid (e.g. 49 different file names). Let's assume the files are simply named like this:
tile_001.lsm tile_002.lsm .... tile_049.lsm
which translates to the following entry tile_{iii}.lsm. It tells the plugin where to put the increasing index number i, and furthermore to use leading zeros with a length of 3. If the tiles would be called tile_1.lsm tile_2.lsm .... tile_49.lsm, it would translate to tile_{i}.lsm."

"If you select 'Filename defined position / Defined by filename as type, the approximate coordinates in the grid should be part of the filename. Assuming your files are called:
tile_x01_y01.lsm tile_x02_y01.lsm .... tile_x10_y10.lsm
it would translate to the following pattern: tile_x{xx}_y{yy}.lsm."

**Comment by StephanPreibisch** [comment]
Oh, an overlap of 0 means nothing will be computed, so I am not sure this is what you want?

**Comment by schroef** [comment]
After looking a bit more in it I did sort understand the naming. Yet I was wondering why the x and y examples still gave errors. 

I think I even tried with overlap. 

I don't need to put x and y in the name right. As long as it gets the coordinates for x and y it should work I guess

**Comment by schroef** [comment]
Yes, i want to put them side to side. 

The problem is with the X and the Y formula part. I just single numbers. 

So if i understand correct the files need to in order from 1 > 64

**Comment by schroef** [comment]
In the page it says; "If you select 'Filename defined position / Defined by filename as type, the approximate coordinates in the grid should be part of the filename. Assuming your files are called:
tile_x01_y01.lsm tile_x02_y01.lsm .... tile_x10_y10.lsm

it would translate to the following pattern: tile_x{xx}_y{yy}.lsm."

I dont see that option however

**Comment by schroef** [comment]
I got it to work now using "stitch grid images".

**Comment by StephanPreibisch** [comment]
Hi, for {x} and {y} to work you need to select "Filename defined position / Defined by filename", otherwise only {i} will work assuming a constant numbering of files.

**Comment by StephanPreibisch** [comment]
Those kind of questions are maybe better asked on the ImageJ mailing list (http://imagej.net/Mailing_Lists), here mostly source code related issues should be discussed

**Comment by ctrueden** [comment]
@StephanPreibisch These days we recommend the [ImageJ Forum](http://forum.imagej.net/) over the NIH ImageJ mailing list, for a [lot of reasons](https://meta.discourse.org/t/discourse-vs-email-mailing-lists/54298). An additional reason beyond those in the article: the clunkiness of confirming each posting to the list, resulting in hours- or days-long delays.

**Comment by schroef** [comment]
Well that option, Filename defined position / Defined by filename, i dont see it in the menu. As i explained it, i solved it using a different menu item.

**Comment by StephanPreibisch** [comment]
There it is ... 
<img width="283" alt="screen shot 2017-08-03 at 19 37 03" src="https://user-images.githubusercontent.com/1420587/28934990-381c553a-7883-11e7-8dd8-36a999e451d7.png">

**Comment by schroef** [comment]
Aha, thanks!

i try that as well. Column by Column got the result i needed using X and Y

–
Rombout

**Comment by StephanPreibisch** [comment]
Ok, great, hope all is good. As @ctrueden mentioned, please address further requests on how to use a specific software to the ImageJ Forum. Thanks a lot.
