### ISSUE TITLE
Calibration in saved stitched images is lost

### ISSUE THREAD

**Issue by manerotoni** [fiji/Stitching#60]
Hello,
I realized that for stitched images saved to disk the calibration is lost. The calibration is present in the original images.

Greetings

Antonio

**Comment by imagejan** [comment]
Thanks for reporting this, @manerotoni! I've seen this behavior for years, but never got around to actually opening an issue about that.

I agree it would be good to have something like:

```
fused.setCalibration(firstTile.getCalibration());
```
