### ISSUE TITLE
Ignoring Z-tile movement in stitching doesn't work

### ISSUE THREAD

**Issue by derekcxu** [fiji/Stitching#62]
The documentation online details that ignoring z is possible by running the following line in script editor:
 
mpicbg.stitching.GlobalOptimization.ignoreZ = true;
 
However, I have found that even when I do this (after setting language to Beanshell, etc, following the instructions), the stitched image still shifts along the z-axis, causing mis-alignment.

I've already contacted Dr. Preibisch who may have already fixed this but asked me to open an issue.

**Comment by StephanPreibisch** [comment]
Hi @derekcxu, this should be fixed with commit https://github.com/fiji/Stitching/commit/b549d44b28c8f05c63f4dab63037a808caf1faf3

Making a release for Fiji now ...

**Comment by StephanPreibisch** [comment]
Hi @ctrueden, the release-version.sh script hangs on my computer after pulling the newest version:

```
../scijava-scripts/release-version.sh 
Version? [3.1.7]: 
Detected DEFAULT version bump
```

Did something change that I missed, am I doing something wrong? Sorry and thanks so much, Stephan

**Comment by StephanPreibisch** [comment]
Hi @ctrueden, this was a VPN issue, please never mind ... sorry! Release worked now ...
