### ISSUE TITLE
Can stitch without blending?

### ISSUE THREAD

**Issue by as-nobu** [fiji/Stitching#72]
Is it possible to simply put the images together in order of registration without blending when compositing images?
When I look at the fuse options, besides linear blending, I see average, median, max intensity, etc. However, as I understand it, these are a kind of blending where the pixel values are calculated according to these algorithms in the overlapping areas of the image. I have also tried the following setting, and the plugin still do some blending in the overlapping areas.
mpicbg.stitching.fusion.BlendingPixelFusion.fractionBlended = 0.0;

**Comment by imagejan** [comment]
You can choose '*Intensity of random input file*' in the Grid Stitching dialog.

**Comment by as-nobu** [comment]
@imagejan Thank you. It looks what I want.
